# Generated by Django 2.2.6 on 2019-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareflatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
    ]
