# Generated by Django 2.2.6 on 2019-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareflatapp', '0002_auto_20191026_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advert',
            name='photo2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advert',
            name='photo3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advert',
            name='photo4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advert',
            name='photo5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advert',
            name='photo6',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
