# Generated by Django 2.2.6 on 2019-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareflatapp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01', verbose_name='Date of Birth'),
        ),
    ]
